server:
  port: 8087

# Spring配置
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.91:8432/baccano-iot
    username: admin
    password: hFbyk%Cc*lFMiwJe
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 192.168.1.91
      port: 8379
      password: hFbyk%Cc*lFMiwJe
      database: 0
  rocketmq:
    name-server: localhost:9876
    producer:
      group: asset-manager-producer
    consumer:
      group: asset-manager-consumer

# MyBatis Plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.baccano.iot.asset.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 资产管理配置
asset:
  manager:
    page-size: 20
    cache-timeout: 3600

# 日志配置
logging:
  level:
    com.baccano.iot.asset: debug
    org.springframework: info