server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://192.168.1.91:8432/baccano-iot
    username: admin
    password: hFbyk%Cc*lFMiwJe
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 192.168.1.91
      port: 8379
      password: hFbyk%Cc*lFMiwJe
      database: 0
  rocketmq:
    name-server: localhost:9876
    producer:
      group: device-manager-producer

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.baccano.iot.device.entity

# Swagger配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'device'
      paths-to-match: '/api/v1/**'
      packages-to-scan: com.baccano.iot.device.controller

# 日志配置
logging:
  level:
    com.baccano.iot.device: debug
