spring:
  main:
    web-application-type: reactive
#  autoconfigure:
#    exclude:
#      - org.springframework.cloud.autoconfigure.LifecycleMvcEndpointAutoConfiguration
  application:
    name: api-gateway
  profiles:
    active: ${ACTIVE_PROFILE:dev}

